Fix: volvemos a la version anterior
Parseamos

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -23,18 +23,18 @@ jobs:
       - name: Set Team Name
         id: set-branch-name
         run: |
-            BRANCH_NAME=${GITHUB_REF#refs/heads/}
-            CLEAN_BRANCH_NAME=${BRANCH_NAME#feature/}
-            echo "CLEAN_BRANCH_NAME=$CLEAN_BRANCH_NAME" >> $GITHUB_ENV
+          BRANCH_NAME=${GITHUB_REF#refs/heads/}
+          CLEAN_BRANCH_NAME=${BRANCH_NAME#feature/}
+          echo "CLEAN_BRANCH_NAME=$CLEAN_BRANCH_NAME" >> $GITHUB_ENV
 
       - name: Identify User of the Team
         id: identify-user
         run: |
-            user=$(git log -1 --pretty=format:'%an')
-            echo "user=$user" >> $GITHUB_ENV
-    
+          user=$(git log -1 --pretty=format:'%an')
+          echo "user=$user" >> $GITHUB_ENV
+
       - name: Display User Name and Team Name
-        run: echo "Push has been performed by the user $user of the Team $CLEAN_BRANCH_NAME"
+        run: echo "Push has been performed by the user ${{ env.user }} of the Team ${{ env.CLEAN_BRANCH_NAME }}"
 
       - name: Set up Node.js
         uses: actions/setup-node@v4
@@ -42,12 +42,10 @@ jobs:
           node-version: '20'
 
       - name: Install markdownlint-cli2
-        run: |
-          npm install -g markdownlint-cli2
+        run: npm install -g markdownlint-cli2
 
       - name: Create markdownlint config
-        run: |
-          echo '{ "MD013": false }' > ./bin/.markdownlint.json
+        run: echo '{ "MD013": false }' > ./bin/.markdownlint.json
 
       - name: Identify Changed Files
         id: changed-files
@@ -69,8 +67,6 @@ jobs:
                 ;;
             esac
           done < changed-files.txt
-        env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Lint Markdown for all Docs
         run: |
@@ -133,19 +129,19 @@ jobs:
       - name: Archive Team ${{ env.CLEAN_BRANCH_NAME }} Linting Results
         uses: actions/upload-artifact@v4
         with:
-            name: markdown-lint-results-team-${{ env.CLEAN_BRANCH_NAME }}
-            path: Resume${{ env.CLEAN_BRANCH_NAME }}.txt
+          name: markdown-lint-results-team-${{ env.CLEAN_BRANCH_NAME }}
+          path: Resume${{ env.CLEAN_BRANCH_NAME }}.txt
 
       - name: Check for Linting Errors in Docs ${{ env.CLEAN_BRANCH_NAME }}
         run: |
-            echo "Checking for linting errors in team summary..."
-            resume_file="Resume${{ env.CLEAN_BRANCH_NAME }}.txt"
-            if [ -f "$resume_file" ] && grep -q "MD" "$resume_file"; then
-              echo "Errors found in $resume_file"
-              exit 1
-            else
-              echo "No linting errors found in team summary."
-            fi
+          echo "Checking for linting errors in team summary..."
+          resume_file="Resume${{ env.CLEAN_BRANCH_NAME }}.txt"
+          if [ -f "$resume_file" ] && grep -q "MD" "$resume_file"; then
+            echo "Errors found in $resume_file"
+            exit 1
+          else
+            echo "No linting errors found in team summary."
+          fi
 
       - name: Trigger Audit
         uses: benc-uk/workflow-dispatch@v1
