Normalizamos el actions y añadimos el modulo de control de errores y las variables por env job y paso

diff --git a/.github/workflows/yamllint.yaml b/.github/workflows/yamllint.yaml
--- a/.github/workflows/yamllint.yaml
+++ b/.github/workflows/yamllint.yaml
@@ -23,53 +23,37 @@ permissions:
   issues: write
   pull-requests: write
 
+env:
+  KAOS_MODULE: "[Ka0S] YAMLLINT"
+  GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
+  KAOS_YAMLLINT_CONFIG: ${{ secrets.KAOS_YAMLLINT_CONFIG }}
+
 jobs:
   yaml-lint-process:
     runs-on: kaos-runner-yamllint
 
     steps:
-      - name: Checkout Repository
-      # Checkout the repository to get the information of the commit
+      - id: repo # Checkout the repository to get the information of the commit
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
           token: ${{ secrets.KAOS_TOKEN }}
-
-      - name: Set Info about Commit temp vars
-        # Set the branch name and team name and file implicit in commit and save it in the environment variable
-        run: |
-          BRANCH_NAME=${{ github.event.base_ref }}
-          USER_NAME=${{ github.actor.name}}
-          USER_EMAIL=${{ github.actor.email }}
-          PATH_RESUME="./core/results/"
-          KAOS_MODULE="[YAML LINT]"
-          KAOS_STEP_MODULE=""
-          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
-          echo "USER_NAME=$USER_NAME" >> $GITHUB_ENV
-          echo "USER_EMAIL=$USER_EMAIL" >> $GITHUB_ENV
-          echo "PATH_RESUME=$PATH_RESUME" >> $GITHUB_ENV
-          echo "KAOS_MODULE=$KAOS_MODULE" >> $GITHUB_ENV
-          echo "KAOS_STEP_MODULE=$KAOS__STEP_MODULE" >> $GITHUB_ENV
-          echo "DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
     
-      - name: Set up Python
+      - id: python
         uses: actions/setup-python@v5
         with:
           python-version: '3.x'
   
-      - name: Install yamllint
+      - id: install-yamllint
         run: |
           python -m pip install yamllint
 
-      - name: Check yaml lint condition
-        env:
-          GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
-          KAOS_YAMLLINT_CONFIG: ${{ secrets.KAOS_YAMLLINT_CONFIG }}
+      - id: check-yaml
         run: |
             # Invocamos la primera comprobación de base, sino se supera el proceso no continua
-            yamllint -c $KAOS_YAMLLINT_CONFIG "${{ github.event.inputs.kaos-files }}" >> core/results/yaml-lint-results-${{ github.run_id }}-${{ env.DATETIME }}.txt || true
+            yamllint -c $KAOS_YAMLLINT_CONFIG "${{ github.event.inputs.kaos-files }}" >> core/results/yaml-lint-results-${{ github.run_id }}.txt || true
               # Check if exist errors in file
-              if [ ! -s .core/results/yaml-lint-results-${{ github.run_id }}-${{ env.DATETIME }}.txt ]; then
+              if [ ! -s .core/results/yaml-lint-results-${{ github.run_id }}.txt ]; then
                 # Todo ha salido bien, añadimos el comentario a la issue y saltamos al siguiente paso
                 KAOS_ISSUE_BODY="The yaml lint process ${{ github.event.inputs.kaos-origin }} launch the check ${{ github.run_id }} and its result has been SUCCESS"
                 gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-title="" -f kaos-issue-body="$KAOS_ISSUE_BODY" -f kaos-issue-actions=comment -f kaos-issue-tag="" -f kaos-issue-id=${{ github.event.inputs.kaos-issue-id }}
@@ -78,21 +62,26 @@ jobs:
                 gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-title="" -f kaos-issue-body="Ka0S approve create pull request for issue ${{ github.event.inputs.kaos-issue-id }}.Please review all files implicated in pull request and approve to merge" -f kaos-issue-actions=comment -f kaos-issue-tag="" -f kaos-issue-id=${{ github.event.inputs.kaos-issue-id }}                
               else
                 # Algo no ha salido bien, añadimos el comentario a la issue y saltamos al siguiente paso
-                KAOS_ISSUE_BODY="The yaml lint process ${{ github.event.inputs.kaos-origin }} launch the check ${{ github.run_id }} and its result has been FAILED, please check core/results/yaml-lint-results-${{ github.run_id }}-${{ env.DATETIME }}.txt"
-                gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-title="" -f kaos-issue-body="$KAOS_ISSUE_BODY" -f kaos-issue-actions=comment -f kaos-issue-tag="" -f kaos-issue-id=${{ github.event.inputs.kaos-issue-id }} -f kaos-issue-body-file=core/results/yaml-lint-results-${{ github.run_id }}-${{ env.DATETIME }}.txt
+                KAOS_ISSUE_BODY="The yaml lint process ${{ github.event.inputs.kaos-origin }} launch the check ${{ github.run_id }} and its result has been FAILED, please check core/results/yaml-lint-results-${{ github.run_id }}.txt"
+                gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-title="" -f kaos-issue-body="$KAOS_ISSUE_BODY" -f kaos-issue-actions=comment -f kaos-issue-tag="" -f kaos-issue-id=${{ github.event.inputs.kaos-issue-id }} -f kaos-issue-body-file=core/results/yaml-lint-results-${{ github.run_id }}.txt
                 # una vez finalizado este proceso, en funcion del modulo donde esta ubicado el ficher que se ha comprobado ejecutara un jobs u otro 
               fi
 
-      - name: Check execution
+  handle_failure:
+    runs-on: 
+      group: kaos-test
+    needs: [yaml-lint-process]
+    if: ${{ failure() }}
+    steps:
+      - id: check-execution
         env:
           GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
-        if: failure()
         run: |
-          echo "Error detected in Ka0S YAMLLINT, creating issue..."
-          KAOS_ISSUE_TITLE="Ka0S YAMLLINT Action Failed: ${{ github.workflow }}"
+          echo "Error detected in Ka0S, creating issue..."
+          KAOS_ISSUE_TITLE="Ka0S Action Failed: ${{ github.workflow }}"
           KAOS_ISSUE_BODY=$(cat <<'EOF'
-          An error occurred in the Ka0S YAMLLINT Action workflow **${{ github.workflow }}**.
-          **[KAOS YAMLLINT]  Message:**
+          An error occurred in the Ka0S Action workflow **${{ github.workflow }}**.
+          **${{ env.KAOS_MODULE }}  Message:**
           \`\`\`
           **Please check the job logs for ${{ secrets.KAOS_ACTIONS_URL }}${{ github.run_id }}**
           \`\`\`
@@ -106,4 +95,4 @@ jobs:
           Please investigate the issue.
           EOF
           )
-          gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-title="$KAOS_ISSUE_TITLE" -f kaos-issue-body="$KAOS_ISSUE_BODY" -f kaos-issue-actions=create -f kaos-issue-tag="bug"
+          gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-title="$KAOS_ISSUE_TITLE" -f kaos-issue-body="$KAOS_ISSUE_BODY" -f kaos-issue-actions=create -f kaos-issue-tag="bug"   
